### ISSUE TITLE
Save/Load of character.Notes improperly handled

### ISSUE THREAD

**Issue by Seferan** [Sebaestschjin/gloomhaven-saveloader#19] opened 2020-06-24 21:14 UTC
I used the Save routine to create a SaveFile.  Upon trying to load, the following section errors indicating that it was expecting a table and got a STRING.   Pastebin: https://pastebin.com/dQFWgupT shows that character.notes is infact a string.

  if character.notes then
    characterSheet.UI.setAttribute("NotesFront", "text", table.concat(character.notes, "\n"))
  end
  if character.hidden_notes then
    characterSheet.UI.setAttribute("Notes", "text", table.concat(character.notes, "\n"))
  end

**Comment by Sebaestschjin** [comment] 2020-06-25 20:54
I think this got "accidentally" fixed with 12b87da, where `notes` and `hidden_notes` are now split into a table. At least I can't reproduce with the current version.

**Closed** 2020-06-28 11:35 UTC
